name = "proxycontroller"
main = "src/index.js"
compatibility_date = "2026-06-03"

# 告诉 Cloudflare 这是一个普通的 Worker
workers_dev = true

# 声明代码中用到的环境变量（用户在部署页面或稍后可以修改）
[vars]
WEB_USER = "admin8355"
WEB_PASS = "Adm7kq29Pz"
PROXY_USER = "proxy8355"
PROXY_PASS = "Pxy8mT46Qv"

# 声明 D1 数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "proxy_db"
database_id = "34047098-4442-4dc9-a75e-64caa7b3463e" # 留空，一键部署向导或后续配置会引导用户绑定他们自己的 D1 数据库
